name: Community_App_Boilerplate
description: This is an open source project for creating a Flutter app that shall serve as a template/boilerplate for various technical communities, clubs, organizations, etc to use . 

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^4.1.2+1
  bordered_text: ^1.0.0
  carousel_slider: ^1.4.1
  speech_to_text: ^2.0.1
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/img.jpeg"


# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/icon/techequilla_app_icon.jpeg
    - assets/icon/techequilla_app_icon_v2.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
